version: "3.8"
services:

#  gateway:
#    image: nginx
#    container_name: nginx
#    ports: 
#      - 8080:8080
#    networks:
#      - backend
 
  auth:
    image: auth:compose_build
    restart: on-failure
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - backend
 #   environment:
 #     - PORT=8081 
    ports:
      - 2109:2109     
    depends_on:
      - auth_baza  

  auth_baza:
#  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
#    volumes:
 #     - ./postgre-volumes:/data/db
    networks:
      - backend

#  auth_baza:
#    build: ./postgres
#    restart: on-failure
#    hostname: postgres
#    container_name: postgres
#    networks:
#      - backend
 #   ports:
 #     - 5432:5432
  #  environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=korisnici
  
     



networks:
  backend:
    name: mreza
    driver: bridge