version: "3.8"
services:


  gateway:
    image: nginx:1.19.8-alpine
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
 
  auth:
    image: auth:compose_build
    restart: on-failure
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - PORT=8081 
#    ports:
#      - 2109:2109     
    depends_on:
      - auth_baza  

  auth_baza:
    image: postgres
    restart: on-failure
    container_name: auth_baza
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
    networks:
      - backend

  user_baza:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - backend
     



networks:
  backend:
    name: mreza
    driver: bridge